services:
    db:
        container_name: ${CONTAINER_NAME}_db
        image: mysql:8.0
        restart: always
        ports: 
            - "3306:3306"
        volumes: 
            - mysql_db:/var/lib/mysql
        environment: 
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        command: --default-authentication-plugin=mysql_native_password

    phpmyadmin:
        container_name: ${CONTAINER_NAME}_phpmyadmin
        image: phpmyadmin
        restart: always
        ports:
            - "8080:80"
        links:
            - db

    server:
        container_name: ${CONTAINER_NAME}_server
        build: 
            args:
                user: ${USER}
                uid: ${UID}
            context: .
        volumes:
            - "${PWD}:/var/www/html"
        ports:
            - "${PORT}:80"
        links:
            - db
        depends_on:
            - db
        environment:
            - TZ=America/Sao_Paulo


volumes:
    mysql_db:
